"""Small UI helpers for the Streamlit dashboard."""

from __future__ import annotations

from datetime import date, datetime, time
from typing import Any

import pandas as pd


DISCLAIMER = (
    "This is a prototype academic advisory generated by an automated research system. "
    "It is NOT an official ICAO warning and must NOT be used for operational "
    "aviation decision-making."
)


def combine_date_time_iso(date_value: date, time_value: time) -> str:
    """Combine separate Streamlit date/time values into an ISO 8601 string."""
    return datetime.combine(date_value, time_value).strftime("%Y-%m-%dT%H:%M:%S")


def historical_risk_windows() -> pd.DataFrame:
    """Recent high-risk geomagnetic storm windows from SERENE Kp/ap data."""
    return pd.DataFrame([
        {
            "Time UTC": "2017-09-08 00:00 to 03:00",
            "Kp": "8.0",
            "ap": "207",
            "Risk": "G4 Severe geomagnetic storm",
            "Select range": "2017-09-08T00:00:00 to 2017-09-08T03:00:00",
        },
        {
            "Time UTC": "2017-09-08 12:00 to 15:00",
            "Kp": "8.3",
            "ap": "236",
            "Risk": "G4 Severe geomagnetic storm",
            "Select range": "2017-09-08T12:00:00 to 2017-09-08T15:00:00",
        },
        {
            "Time UTC": "2023-03-24 03:00 to 06:00",
            "Kp": "8.0",
            "ap": "207",
            "Risk": "G4 Severe geomagnetic storm",
            "Select range": "2023-03-24T03:00:00 to 2023-03-24T06:00:00",
        },
        {
            "Time UTC": "2023-04-23 18:00 to 21:00",
            "Kp": "8.3",
            "ap": "236",
            "Risk": "G4 Severe geomagnetic storm",
            "Select range": "2023-04-23T18:00:00 to 2023-04-23T21:00:00",
        },
        {
            "Time UTC": "2023-04-24 03:00 to 06:00",
            "Kp": "8.0",
            "ap": "207",
            "Risk": "G4 Severe geomagnetic storm",
            "Select range": "2023-04-24T03:00:00 to 2023-04-24T06:00:00",
        },
        {
            "Time UTC": "2024-03-24 15:00 to 18:00",
            "Kp": "8.3",
            "ap": "236",
            "Risk": "G4 Severe geomagnetic storm",
            "Select range": "2024-03-24T15:00:00 to 2024-03-24T18:00:00",
        },
        {
            "Time UTC": "2024-05-10 18:00 to 2024-05-11 18:00",
            "Kp": "9.0",
            "ap": "400",
            "Risk": "G5 Extreme geomagnetic storm",
            "Select range": "2024-05-10T18:00:00 to 2024-05-11T18:00:00",
        },
        {
            "Time UTC": "2024-08-12 12:00 to 15:00",
            "Kp": "8.0",
            "ap": "207",
            "Risk": "G4 Severe geomagnetic storm",
            "Select range": "2024-08-12T12:00:00 to 2024-08-12T15:00:00",
        },
        {
            "Time UTC": "2024-10-10 18:00 to 2024-10-11 03:00",
            "Kp": "8.7",
            "ap": "300",
            "Risk": "G4 Severe geomagnetic storm",
            "Select range": "2024-10-10T18:00:00 to 2024-10-11T03:00:00",
        },
        {
            "Time UTC": "2025-01-01 15:00 to 18:00",
            "Kp": "8.0",
            "ap": "207",
            "Risk": "G4 Severe geomagnetic storm",
            "Select range": "2025-01-01T15:00:00 to 2025-01-01T18:00:00",
        },
        {
            "Time UTC": "2025-11-12 00:00 to 06:00",
            "Kp": "8.7",
            "ap": "300",
            "Risk": "G4 Severe geomagnetic storm",
            "Select range": "2025-11-12T00:00:00 to 2025-11-12T06:00:00",
        },
        {
            "Time UTC": "2026-01-19 18:00 to 2026-01-20 00:00",
            "Kp": "8.7",
            "ap": "300",
            "Risk": "G4 Severe geomagnetic storm",
            "Select range": "2026-01-19T18:00:00 to 2026-01-20T00:00:00",
        },
    ])


def generate_historical_risk_alerts(start_time: str | None, end_time: str | None) -> pd.DataFrame:
    """Create advisories when the selected range overlaps known storm windows."""
    selected_start = _parse_datetime(start_time)
    selected_end = _parse_datetime(end_time)
    if selected_start is None or selected_end is None:
        return pd.DataFrame()
    if selected_start > selected_end:
        selected_start, selected_end = selected_end, selected_start

    alerts: list[dict[str, Any]] = []
    for _, window in historical_risk_windows().iterrows():
        window_start, window_end = _parse_range(str(window["Select range"]))
        if window_start is None or window_end is None:
            continue
        if selected_start <= window_end and selected_end >= window_start:
            risk_text = str(window["Risk"])
            risk_level = _extract_risk_level(risk_text)
            reason = (
                f"Selected range overlaps historical {risk_text} window "
                f"({window['Select range']}); Kp {window['Kp']}, ap {window['ap']}."
            )
            alerts.append({
                "timestamp": window["Time UTC"],
                "region": "Global",
                "alert_type": "Historical geomagnetic storm window",
                "risk_level": risk_level,
                "value": window["Kp"],
                "threshold_info": reason,
                "reason": reason,
                "possible_aviation_impact": (
                    "Historical geomagnetic storm conditions may affect GNSS and HF systems."
                ),
                "interpretation": (
                    "This advisory is based on the selected time range matching a known "
                    "high-risk geomagnetic storm window, not on the point-based SERENE "
                    "API values alone."
                ),
                "disclaimer": DISCLAIMER,
            })

    if not alerts:
        return pd.DataFrame()
    return pd.DataFrame(alerts)


def _parse_range(value: str) -> tuple[pd.Timestamp | None, pd.Timestamp | None]:
    start_text, sep, end_text = value.partition(" to ")
    if not sep:
        return None, None
    return _parse_datetime(start_text), _parse_datetime(end_text)


def _extract_risk_level(risk_text: str) -> str:
    parts = risk_text.split()
    if len(parts) >= 2 and parts[0].startswith("G"):
        return " ".join(parts[:2])
    return "Warning"


def _parse_datetime(value: str | None) -> pd.Timestamp | None:
    if not value:
        return None
    try:
        parsed = pd.to_datetime(value)
    except (TypeError, ValueError):
        return None
    if pd.isna(parsed):
        return None
    return parsed
